CREATE TABLE classificacao (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO classificacao (nome) VALUES ('CASA'),('TRABALHO'),('ESTUDOS'),('LAZER'),('OUTROS');